import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Tej
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        XMLTree feeds = new XMLTree1(url);
        String title = feeds.child(0).attributeValue("name");
        String feedTitle = "";
        String feedURL = "";
        String feedFile = "";
        SimpleWriter fileIO = new SimpleWriter1L();
        int feedCount = feeds.numberOfChildren();

        out.println("<html><head><title>" + title + "</title></head><body><h2>"
                + title + "</h2>");

        out.println("<ul>");

        for (int i = 0; i < feeds.numberOfChildren(); i++) {
            feedTitle = feeds.child(i).attributeValue("name");
            feedURL = feeds.child(i).attributeValue("url");
            feedFile = feeds.child(i).attributeValue("file");
            XMLTree feedXML = new XMLTree1(feedURL);
            fileIO = new SimpleWriter1L(feedFile);
            outputHeader(feedXML.child(0), fileIO);
            outputFooter(fileIO);
            out.println("<li><a href=\"" + feedFile + ">" + feedTitle
                    + "</a></li>");

        }

    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //set tite of html page
        String title = "";
        if (getChildElement(channel, "title") > -1) {
            title = channel.child(getChildElement(channel, "title")).child(0)
                    .label();
        } else {
            title = "Empty Title";
        }

        //set description of html page
        String description = "";
        if (channel.child(getChildElement(channel, "description"))
                .numberOfChildren() < 1) {
            description = "No Description.";
        } else {
            description = channel.child(getChildElement(channel, "description"))
                    .child(0).label();
        }
        String link = channel.child(getChildElement(channel, "link")).child(0)
                .label();

        //opening and heading of html page

        out.println("<html>");
        out.println("<head>");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1><a href=\"" + link + "\">" + title + "</a></h1>");
        out.println("<p>" + description + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");

        //loop processItem(tables) until no more item tages
        for (int i = 0; i < channel.numberOfChildren(); i++) {
            if (channel.child(i).label().equals("item")) {
                processItem(channel.child(i), out);
            }
        }

    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";
        int index = -1;
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (index == -1 && xml.child(i).label().equalsIgnoreCase(tag)
                    & xml.child(i).isTag()) {
                index = i;
            }
        }
        return index;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //start table
        out.println("<tr>");

        //get pubDate
        String pubDate = "";
        if (item.child(getChildElement(item, "pubDate"))
                .numberOfChildren() < 1) {
            pubDate = "No Date Available";
        } else {
            pubDate = item.child(getChildElement(item, "pubDate")).child(0)
                    .label();
        }
        out.println("<td>" + pubDate + "</td>");

        //get source and source URL
        int sourceLoc = getChildElement(item, "source");
        String source = "No Source Available.";
        String sourceURL = "";

        if (sourceLoc > -1) {
            source = item.child(sourceLoc).child(0).label();
            sourceURL = item.child(sourceLoc).attributeValue("url");
            out.println(
                    "<td><a href=\"" + sourceURL + "\">" + source + "</td>");

        } else {
            out.println("<td>" + source + "</td>");
        }

        //get item description
        //THIS DOES NOT WORK IF YOU ARE TESTING WITH THE YAHOO RSS FEED

        /*
         * String news = "No Description"; if (item.child(getChildElement(item,
         * "description")) .numberOfChildren() > 0) { news =
         * item.child(getChildElement(item, "description")).child(0) .label(); }
         */

        //get title
        String title = "No Title";
        if (item.child(getChildElement(item, "title")).numberOfChildren() > 0) {
            title = item.child(getChildElement(item, "title")).child(0).label();
        }

        String link = "";
        if (item.child(getChildElement(item, "link")).numberOfChildren() > 0) {
            link = item.child(getChildElement(item, "link")).child(0).label();
        }

        //print link and title
        // SUPPOSE TO PRINT DESCRIPTION BUT IT DOES NOT WORK WITH YAHOO RSS FEED
        out.println("<th><a href=\"" + link + "\">" + title + "</th>");

        //close table tag
        out.println("</tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();
        SimpleWriter finalFileIO = new SimpleWriter1L("output.html");
        int xmlValid = -1;
        out.print("Enter the URL of a RSS file: ");
        String inURL = in.nextLine();
        XMLTree xml = new XMLTree1(inURL);

        processFeed(inURL, "", finalFileIO);

        in.close();
        out.close();
    }

}